export const skills: string[] = [
  "JavaScript",
  "TypeScript",
  "React",
  "C++",
  "C#",
  "C",
  "Java",
  "Unity",
  "Unreal Engine",
  "Phaser",
  "Blender",
  "Python",
  "HTML",
  "CSS",
  "Git",
  "WebGL",
  "Windows",
  "Ubuntu",
  "macOS",
  "Premiere Pro",
  "Inkscape",
  "Game Development",
];

export const languages: string[] = ["English", "Spanish", "French"];
